O curso irá trabalhar <br>
.Numpy <br>
.Pandas <br>
.Scipy <br>
.Matplotlib <br>
lazyprogrammer.me/numpy

In [1]:
#numpy constrói a estrutura básica, o array, para qualquer outra coisa da área de Machine Learning
#numpy serve para colocar matemática em código
import numpy as np

Dot product é multiplicar um vetor, elemento a elemento, por outro e em seguida somar os resultados <br>
Mesma característica de multiplicação de matrizes

# LISTAS E ARRAYS

In [2]:
L = [1,2,3]
A = np.array(L)

In [3]:
#loop itens em uma lista
for e in L:
    print(e)

1
2
3


In [4]:
#loop intens em um array
for e in A:
    print(e)

1
2
3


In [5]:
#adicionar elementos em lista
L.append(4)
L

[1, 2, 3, 4]

In [6]:
L + [5]

[1, 2, 3, 4, 5]

In [7]:
#adicionarelementos em um array
# A.append(4) # - DÁ ERRO - Array é imutável

In [8]:
#somar um array se chama "broadcasting"
#broadcasting vai somar elemento a elemento
A + np.array([4])

array([5, 6, 7])

In [9]:
#soma de vetores de mesmo tamanho
A + np.array([4,5,6])

array([5, 7, 9])

In [10]:
#ERRO
#A + np.array([4,5]) # vai dar errado porque os vetores possuem tamanhos diferentes

In [11]:
#Multiplicar lista por escalar INTEIRO, repete a lista, não-inteiro dá ERRO
2*L # = L+L

[1, 2, 3, 4, 1, 2, 3, 4]

In [12]:
# Multiplicar array por escalar INTEIRO, não-inteiro FUNCIONA TAMBÉM
2*A # = A+A

array([2, 4, 6])

In [13]:
#broadcasting com lista
L2 = []
for e in L:
    L2.append(e+3)
L2

[4, 5, 6, 7]

In [14]:
# comprehension
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [15]:
#Numpy array suporta potência
A**2

array([1, 4, 9], dtype=int32)

In [16]:
# lista não suporta potência, tem que usar iteração
# L**2 # DÁ ERRO
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [17]:
#log
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [18]:
#exponencial
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [19]:
#tangente hiperbólica
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

Em resumo: <br>
Uma lista parece um array, mas é uma estrutura de dados comum <br>
Um numpy array existe para fazer matemática

# The DOT product ou Inner Product

In [20]:
a = np.array([1,2])
b = np.array([3,4])

In [21]:
#calculando dot produict usando zip
dot = 0
for e,f in zip(a,b):
    dot += e*f
dot

11

In [22]:
#calculando dot product com indexing
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [23]:
#elementwise multiplication
a * b

array([3, 8])

In [24]:
#calculando dot product somando a elementwise mutliplication
np.sum(a*b)

11

In [25]:
# as funções também são instance methods
(a*b).sum()

11

In [26]:
#função dot product
a.dot(b)

11

In [27]:
#declaração alternativa
np.dot(a,b)

11

In [28]:
#declaração alternativa
a @ b

11

In [29]:
# magnitude(A) = raiz quadrada da soma de todos os elementros do vetor A ao quadrado
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [30]:
#método de magnitude do numpy
np.linalg.norm(a)

2.23606797749979

In [31]:
# cos(theta) = ( transpose(a) * b ) / magnitude(a) * magnitude(b), sendo theta o ângulo entre a e b
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [32]:
#para encontrar o ângulo em radianos
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Speed test

In [33]:
from datetime import datetime

In [34]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000
len(a)

100

In [35]:
def slow_dot_product(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e*f
    return result

In [36]:
#método devagar
t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0
#método rápido
t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0
print("dt1 / dt2:",dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 94.91095204725198


In [37]:
#alternativa para medir o tempo
%timeit
slow_dot_product(a,b)

-10.99351573460657

In [38]:
#alternativa para medir o tempo
%time
a @ b

Wall time: 0 ns


-10.993515734606571

# Matrices
2d arrays <br>
O objeto matriz do numpy sempre terá obrigatoriamente 2 dimensões <br>
É interessante converter matrizes para arrays antes de trabalhar nelas <br>

In [39]:
#uma matriz pode parecer uma lista de listas
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [40]:
L[0]

[1, 2]

In [41]:
# Primeiro linhas, depois colunas
L[0][1]

2

In [42]:
#converte para np.array, o que deixa no formato de matriz (atenção em como aparece)
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [43]:
#slice o primeiro elemento
A[0]

array([1, 2])

In [44]:
#slice o segundo elemento do primeiro elemento
A[0][1]

2

In [45]:
#notação melhor
A[0,1]

2

In [46]:
#seleciona todas as linhas da coluna zero coluna
A[:,0]

array([1, 3])

In [47]:
#transposta
A.T

array([[1, 3],
       [2, 4]])

In [48]:
#exponencial em todos os elementos
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [49]:
#se aplicado à lista numpy trata como erray e devolve array
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [50]:
#multiplicação de matrizes = generalização do dot product
B = np.array([[1,2,3],[4,5,6]])
A @ B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [51]:
#determinante
np.linalg.det(A)

-2.0000000000000004

In [52]:
# inversa
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [53]:
#prova real inversa, não fica exatamente zero na coluina secundária, porque o computador não tem precisão perfeita
#por isso o determinante também não deu exatamente -2
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [54]:
# traço
np.trace(A)

5

In [55]:
# diagonal da matriz
np.diag(A)

array([1, 4])

In [56]:
# função diagonal com um vetor cria uma matriz com o vetor na diagonal (matriz diagonal)
# a função é overloaded, se coloca uma matriz recebe vetor, se coloca um vetor recebe matriz
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [57]:
# função de eigen values traz os aigen values e eigen vectors
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [58]:
#unpacking eigen values e vectors
Lam, V = np.linalg.eig(A)
print(Lam,"-->",V)

[-0.37228132  5.37228132] --> [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [59]:
# fazendo check de true ou false elementwise 
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [60]:
# fazendo o check, o valor False é resultado de arredondamento
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [61]:
#para comparar se dois vetores são iguais sem o erro de arredondamento
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [62]:
# mesma comparação com matrizes
np.allclose(V @ np.diag(Lam), A @ V)

True

# Resolvendo sistemas lineares

 X1 + X2 = 2200 <br>
 1.5*X1 + 4*X2 = 5050 <br>
 <br>
 Forma vetorial: <br>
 x = (X1,X2) <br>
 A = ((1,1),(1.5,4)) <br>
 b = (2200, 5050) <br>
<br>
Resolução de problemas lineares <br>
A*x = b <-> x = A^(-1) * b
 

In [63]:
#jeito eficiente não usa o inverso, usa a função solve
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

x = np.linalg.solve(A,b)
x

array([1500.,  700.])

In [64]:
#testando o jeito ineficiente
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Gerando dados

In [65]:
#array de zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
#array de 1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
#array de 10
np.ones((2,3)) * 10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [68]:
# identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
#arrays de números aleatórios entre 0 e 1
np.random.random((2,3))

array([[0.56198834, 0.25738947, 0.66474733],
       [0.82962928, 0.08191349, 0.84974744]])

In [70]:
# distribuição normal (gaussiana) padrão, média = 0 e var = 1
# detalhe: o input não é uma tupla
np.random.randn(2,3)

array([[-0.77839784,  0.98300343, -0.76060905],
       [ 2.3956115 , -0.15939634,  0.1726653 ]])

In [71]:
#testando média  e variância
R = np.random.randn(10000)
print(R.mean(),R.var(), R.std())

-0.013249375379079586 1.0044493689436798 1.002222215351306


In [72]:
#método overloaded, funciona com outra declaração para a mesma classe
R.var() == np.var(R)

True

In [73]:
R = np.random.randn(10000, 3)
R

array([[ 1.13853843, -0.4702011 ,  0.2567281 ],
       [ 0.17759221,  0.30414892,  0.61344946],
       [ 1.88371304,  1.10721594,  0.52446618],
       ...,
       [-1.52502957, -2.18229272, -0.29478354],
       [-0.28851854, -0.87417692,  1.03159502],
       [ 0.10155183, -0.20757328,  0.2253939 ]])

In [74]:
# média de cada coluna
R.mean(axis=0)

array([ 0.00265765, -0.0026765 ,  0.01556529])

In [75]:
# média de cada linha
R.mean(axis=1)

array([ 0.30835514,  0.36506353,  1.17179839, ..., -1.33403527,
       -0.04370015,  0.03979082])

In [76]:
#comprovando número de linhas
R.mean(axis=1).shape

(10000,)

In [77]:
# tratando cada coluna como um vetor não é convenção, mas é o que é feito nesta célula
# o análogo para a variância entre duas colunas, aplicado para mais colunas, é a cov
np.cov(R).shape

(10000, 10000)

In [78]:
#para usar Scikit, Tensorflow ou Pytorch é possível resolver 
# a questão de toda a coluna ser vetor (o correto é ser a linha) transpondo
# observa-se que fica próximo à matriz identidade
np.cov(R.T)

array([[ 1.00375522e+00, -1.16673118e-03, -1.20620052e-02],
       [-1.16673118e-03,  9.72801079e-01,  9.22621816e-04],
       [-1.20620052e-02,  9.22621816e-04,  1.00106099e+00]])

In [79]:
#mesma resposta do que transpor é usar rowvar=False
np.cov(R,rowvar=False)

array([[ 1.00375522e+00, -1.16673118e-03, -1.20620052e-02],
       [-1.16673118e-03,  9.72801079e-01,  9.22621816e-04],
       [-1.20620052e-02,  9.22621816e-04,  1.00106099e+00]])

In [80]:
#a convenção em Python é o intervalo superior não ser inclusivo
#randint vai usar aleatórios inteiros dentro do intervalo especificado
np.random.randint(0,10,size=(3,3))

array([[1, 1, 9],
       [8, 3, 0],
       [4, 4, 3]])

In [81]:
# choice escolhe de um array unidimensional, se colocar um escalar funciona igual randint, como abaixo
np.random.choice(10, size=(3,3))

array([[4, 3, 2],
       [7, 1, 5],
       [2, 3, 6]])

In [82]:
#escolhjendo de um unidimensional b
np.random.choice(b, size=(3,3))

array([[2200, 2200, 5050],
       [2200, 2200, 5050],
       [5050, 5050, 2200]])